
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@6.4.1
dist: xenial
addons:
  apt:
    sources:
      - google-chrome
    packages:
    - google-chrome-stable
