language : node_js
node_js:
    "10"
sudo: required
services:
  - docker 

before_install:
- docker pull paulparas/nightwatch-docker-bootstrapper:v2.0
- docker run paulparas/nightwatch-docker-bootstrapper:v2.0
